{
  "architectures": [
    "InternHVLForConditionalGeneration"
  ],
  "auto_map": {
    "AutoConfig": "configuration_intern_h_vl.InternHVLConfig",
    "AutoModel": "modeling_intern_h_vl.InternHVLForConditionalGeneration",
    "AutoModelForCausalLM": "modeling_intern_h_vl.InternHVLForConditionalGeneration"
  },
  "downsample_ratio": 0.5,
  "dynamic_image_size": true,
  "force_image_size": 448,
  "hidden_size": 5120,
  "image_fold": null,
  "max_dynamic_patch": 12,
  "min_dynamic_patch": 1,
  "model_type": "intern_h_vl",
  "pad2square": false,
  "ps_version": "v2",
  "select_layer": -1,
  "system_message": null,
  "template": "internvl2_5",
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": null,
  "use_backbone_lora": 0,
  "use_llm_lora": 0,
  "use_thumbnail": true,
  "text_config": {
    "_attn_implementation_autoset": true,
    "architectures": [
      "NemotronHForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0.0,
    "attention_head_dim": 128,
    "auto_map": {
      "AutoConfig": "configuration_nemotron_h.NemotronHConfig",
      "AutoModelForCausalLM": "modeling_nemotron_h.NemotronHForCausalLM"
    },
    "bos_token_id": 1,
    "chunk_size": 128,
    "conv_kernel": 4,
    "eos_token_id": 2,
    "expand": 2,
    "hidden_dropout": 0.0,
    "hidden_size": 5120,
    "hybrid_override_pattern": "M-M-M-M*-M-M-M-M*-M-M-M-M*-M-M-M-M*-M-M-M-M*-M-M-M-M*-M-M-M-M-",
    "layers_block_type": ["mamba", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "attention", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "attention", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "attention", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "attention", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "attention", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "attention", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "mlp", "mamba", "mlp"],
    "initializer_range": 0.02,
    "intermediate_size": 20480,
    "layer_norm_epsilon": 1e-05,
    "mamba_head_dim": 80,
    "mamba_hidden_act": "silu",
    "mamba_num_heads": 128,
    "mamba_proj_bias": false,
    "max_position_embeddings": 131072,
    "mlp_bias": false,
    "mlp_hidden_act": "relu2",
    "model_type": "nemotron_h",
    "n_groups": 8,
    "num_attention_heads": 40,
    "num_hidden_layers": 62,
    "num_key_value_heads": 8,
    "num_logits_to_keep": 1,
    "pad_token_id": 0,
    "rescale_prenorm_residual": true,
    "residual_in_fp32": false,
    "rms_norm_eps": 1e-05,
    "sliding_window": null,
    "ssm_state_size": 128,
    "tie_word_embeddings": false,
    "time_step_floor": 0.0001,
    "time_step_limit": [
      0.0,
      Infinity
    ],
    "time_step_max": 0.1,
    "time_step_min": 0.001,
    "time_step_rank": 256,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.51.3",
    "use_bias": false,
    "use_cache": true,
    "use_conv_bias": true,
    "use_mamba_kernels": true,
    "vocab_size": 132096
  },
  "vision_config": {
    "_attn_implementation_autoset": true,
    "_name_or_path": "OpenGVLab/InternViT-6B-448px-V1-5",
    "add_cross_attention": false,
    "architectures": [
      "InternVisionModel"
    ],
    "attention_dropout": 0.0,
    "auto_map": {
      "AutoConfig": "configuration_intern_vit.InternVisionConfig",
      "AutoModel": "modeling_intern_vit.InternVisionModel"
    },
    "bad_words_ids": null,
    "begin_suppress_tokens": null,
    "bos_token_id": null,
    "capacity_factor": 1.2,
    "chunk_size_feed_forward": 0,
    "cross_attention_hidden_size": null,
    "decoder_start_token_id": null,
    "diversity_penalty": 0.0,
    "do_sample": false,
    "drop_path_rate": 0.1,
    "dropout": 0.0,
    "early_stopping": false,
    "encoder_no_repeat_ngram_size": 0,
    "eos_token_id": null,
    "eval_capacity_factor": 1.4,
    "exponential_decay_length_penalty": null,
    "finetuning_task": null,
    "forced_bos_token_id": null,
    "forced_eos_token_id": null,
    "hidden_act": "gelu",
    "hidden_size": 1024,
    "id2label": {
      "0": "LABEL_0",
      "1": "LABEL_1"
    },
    "image_size": 448,
    "initializer_factor": 0.1,
    "initializer_range": 1e-10,
    "intermediate_size": 4096,
    "is_decoder": false,
    "is_encoder_decoder": false,
    "label2id": {
      "LABEL_0": 0,
      "LABEL_1": 1
    },
    "laux_allreduce": "all_nodes",
    "layer_norm_eps": 1e-06,
    "length_penalty": 1.0,
    "max_length": 20,
    "min_length": 0,
    "model_type": "intern_vit_6b",
    "moe_coeff_ratio": 0.5,
    "moe_intermediate_size": 768,
    "moe_output_scale": 4.0,
    "no_repeat_ngram_size": 0,
    "noisy_gate_policy": "RSample_before",
    "norm_type": "layer_norm",
    "num_attention_heads": 16,
    "num_beam_groups": 1,
    "num_beams": 1,
    "num_channels": 3,
    "num_experts": 8,
    "num_hidden_layers": 24,
    "num_return_sequences": 1,
    "num_routed_experts": 4,
    "num_shared_experts": 4,
    "output_attentions": false,
    "output_hidden_states": false,
    "output_scores": false,
    "pad_token_id": null,
    "patch_size": 14,
    "prefix": null,
    "problem_type": null,
    "pruned_heads": {},
    "qk_normalization": false,
    "qkv_bias": true,
    "remove_invalid_values": false,
    "repetition_penalty": 1.0,
    "return_dict": true,
    "return_dict_in_generate": false,
    "sep_token_id": null,
    "shared_expert_intermediate_size": 3072,
    "suppress_tokens": null,
    "task_specific_params": null,
    "temperature": 1.0,
    "tf_legacy_loss": false,
    "tie_encoder_decoder": false,
    "tie_word_embeddings": true,
    "tokenizer_class": null,
    "top_k": 50,
    "top_p": 1.0,
    "torch_dtype": "bfloat16",
    "torchscript": false,
    "transformers_version": "4.48.3",
    "typical_p": 1.0,
    "use_bfloat16": true,
    "use_flash_attn": true,
    "use_moe": false,
    "use_residual": true,
    "use_rts": false,
    "use_weighted_residual": false
  }
}
